<style>
    .oneclick-button
    {
        background-image: none;
        background: #1979c3;
        border: 1px solid #1979c3;
        color: #fff;
        cursor: pointer;
        display: inline-block;
        font-family: 'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;
        font-weight: 600;
        box-sizing: border-box;
        vertical-align: middle;
        float: left;
        line-height: 2.2rem;
        padding: 14px 17px;
        font-size: 1.8rem;
        margin-bottom: 15px;
        width: 49%;
        border-radius: 3px;
        width: 100% !important;
        height: 50px !important;
        border-radius: 8px !important;
        font-weight: 700 !important;
        font-size: 18px !important;
        background-color: #e82e81 !important;
        color: white !important;
        cursor: pointer !important;
        display: flex !important;
        -webkit-box-align: center !important;
        align-items: center !important;
        -webkit-box-pack: center !important;
        justify-content: center !important;
        border: 1px solid #e82e81 !important;
        outline-color: transparent !important;
        margin-bottom: 0.5rem !important;
        text-decoration: none !important;
    }
    .action,.primary
    {
        float: left;
    }
    .qp-custom-mage-design{
      width: 45%;
      padding:0px !important;
      height: 80vh;
    }
    .qp8911_modal-body{
      height: 100%;
    }
</style>
<style>

/* The qp8911_modal (background) */
.qp8911_modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1000; /* Sit on top */
  padding-top: 100px; /* Location of the box */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: #00000099; /* Black w/ opacity */
}
/* qp8911_modal Content */
.qp8911_modal-content {
  background-color: #fefefe;
  margin: auto;
  padding: 10px;
  border: 1px solid #888;
  width: 30%;
}
/* The Close Button */
.close {
  color: #aaaaaa;
  float: right;
  font-size: 28px;
  font-weight: bold;
}
.close:hover,
.close:focus {
  color: #000;
  text-decoration: none;
  cursor: pointer;
}
.qp8911_modal-dialog.qp8911_modal-dialog-centered{
   display: flex;
}
@media screen and (max-width: 768px) {
    .qp8911_modal-content {
        width: 90%;
    }
}
.qp8911_modal-body {
    overflow-y: auto;
}
</style>
<p class="oneclick-button" onclick="triggerIFrame()">QisstPay OneClick</p>
<?php
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$registry = $objectManager->get('\Magento\Framework\Registry');
$currentProduct = $registry->registry('current_product');
$product = $objectManager->create('\Magento\Catalog\Model\Product')->load($currentProduct->getId());
$product_qty = 1;
$eavConfig = $objectManager->get('\Magento\Eav\Model\Config');
$attribute = $eavConfig->getAttribute('catalog_product', 'color');
$options = $attribute->getSource()->getAllOptions();
$sandboxtoken='WjcbAvjYPEOjqNiVb6sF4aRPYhttzuuVu5cIUgPkSHl5MqKUS446f61h9ml8';
$identity_token = 'eyJpdiI6InlrdSthYVFvcjJxMC9nY015WS9NN0E9PSIsInZhbHVlIjoiUURHNE5jU2FaMDJ6KytHeTlFc0E4U0xTYVBvSzd0aDRXcFVsUDB5OEVSMjMxYmdqUldUdmNXS2xBN09JbWVyaTdGZE9WNGNlb0VFNGEyR3IvbVJIZXc9PSIsIm1hYyI6IjkyMzc0NGVhYjc5ODQzMTIzNTcyYTlhNWEzZmFiNDc4NWU5NDI0MzI1NjhiZGM1ODEwODNkMDIxMWNkNzU4ZGEiLCJ0YWciOiIifQ==';
$values = 'products=[{"id":"'.$currentProduct->getId().'","src":"https:pellelusso.com/wp-content/themes/woodmart/images/lazy.png","quantity":"1","attributes":[],"price":"1500","title":"QP"}]&price=1500&currency=PKR&url=https://pellelusso.com/wp-json/qisstpay/teez/&shipping_total=0&tax=0&shipping_methods=[]';
$params = '[{"id":"'.$currentProduct->getId().'","src":"https://fazalsons.pk/wp-content/uploads/2022/02/TCL-300x300.png","quantity":"1","attributes":[],"price":"1500","title":"QP"}]&price=1500&currency=PKR&url=https://fazalsons.pk/wp-json/qisstpay/teez/&shipping_total=0&tax=0&shipping_methods=[{"title":"Local pickup","cost":""},{"title":"Free shipping","cost":0}]';
$qs='eyJpdiI6Inl4RGE0dVo4L2pUTndkOS92dnpzVUE9PSIsInZhbHVlIjoiTkt0VGJ4Nm5BZHMxOXFDRU9OYi92S2FZVHJ1YWhFbjlGZTRBN2JLT2lucGsvNmhDRHJwM2NWNlFiVkJmYkw1bFBCSnluYnVUb1RXUXdmTkF6ZHR3dlE9PSIsIm1hYyI6IjlmNDE5YmI5YjVkZGRhZTM0MDFhZWY4NjdhZmMzZmI2MGM0ODhmMjc3YzY2NDVlMTUyOTg4MGQyNjlhNGZiZjIiLCJ0YWciOiIifQ==&queryUrl=cHJvZHVjdHM9W3siaWQiOiIxNTk0Iiwic3JjIjoiaHR0cHM6Ly9zYW5kYm94LndvcmRwcmVzcy5xaXNzdHBheS5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMjEvMTEvNjY2NjY2NjY2NjY2LmpwZWciLCJxdWFudGl0eSI6IjEiLCJhdHRyaWJ1dGVzIjpbeyJhdHRyaWJ1dGVfcGFfdGVzdC1hdHQiOiJibHVlIiwidmFyaWF0aW9uX2lkIjoiMzkzNSJ9XSwicHJpY2UiOjE2MDAsInRpdGxlIjoiU2hpcnQifV0mcHJpY2U9MTYwMCZjdXJyZW5jeT1QS1ImdXJsPWh0dHBzOi8vc2FuZGJveC53b3JkcHJlc3MucWlzc3RwYXkuY29tL3dwLWpzb24vcWlzc3RwYXkvdGVlei8mc2hpcHBpbmdfdG90YWw9MjAwJnRheD0zNiZzaGlwcGluZ19tZXRob2RzPVt7InRpdGxlIjoiRmxhdCByYXRlIiwiY29zdCI6IjIwMCJ9LHsidGl0bGUiOiJMb2NhbCBwaWNrdXAiLCJjb3N0IjoiMzUwIn0seyJ0aXRsZSI6IkZyZWUgc2hpcHBpbmciLCJjb3N0IjowfV0=';
$qs='eyJpdiI6Inl4RGE0dVo4L2pUTndkOS92dnpzVUE9PSIsInZhbHVlIjoiTkt0VGJ4Nm5BZHMxOXFDRU9OYi92S2FZVHJ1YWhFbjlGZTRBN2JLT2lucGsvNmhDRHJwM2NWNlFiVkJmYkw1bFBCSnluYnVUb1RXUXdmTkF6ZHR3dlE9PSIsIm1hYyI6IjlmNDE5YmI5YjVkZGRhZTM0MDFhZWY4NjdhZmMzZmI2MGM0ODhmMjc3YzY2NDVlMTUyOTg4MGQyNjlhNGZiZjIiLCJ0YWciOiIifQ==';
$qurl='cHJvZHVjdHM9W3siaWQiOiIxNTk0Iiwic3JjIjoiaHR0cHM6Ly9zYW5kYm94LndvcmRwcmVzcy5xaXNzdHBheS5jb20vd3AtY29udGVudC91cGxvYWRzLzIwMjEvMTEvNjY2NjY2NjY2NjY2LmpwZWciLCJxdWFudGl0eSI6IjEiLCJhdHRyaWJ1dGVzIjpbeyJhdHRyaWJ1dGVfcGFfdGVzdC1hdHQiOiJibHVlIiwidmFyaWF0aW9uX2lkIjoiMzkzNSJ9XSwicHJpY2UiOjE2MDAsInRpdGxlIjoiU2hpcnQifV0mcHJpY2U9MTYwMCZjdXJyZW5jeT1QS1ImdXJsPWh0dHBzOi8vc2FuZGJveC53b3JkcHJlc3MucWlzc3RwYXkuY29tL3dwLWpzb24vcWlzc3RwYXkvdGVlei8mc2hpcHBpbmdfdG90YWw9MjAwJnRheD0zNiZzaGlwcGluZ19tZXRob2RzPVt7InRpdGxlIjoiRmxhdCByYXRlIiwiY29zdCI6IjIwMCJ9LHsidGl0bGUiOiJMb2NhbCBwaWNrdXAiLCJjb3N0IjoiMzUwIn0seyJ0aXRsZSI6IkZyZWUgc2hpcHBpbmciLCJjb3N0IjowfV0=';
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl();  // to get Base Url
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');//get current product
$proid = $product->getId();
$proname = $product->getName();
$proimage = "tooni/pub/media/catalog/product".$product->getData('image');
$proquantity = 1;
$proprice = $product->getPrice();
$protitle = $product->getData('name');
$attributes = $product->getAttributes();
$curl = curl_init();
$apiurl = $baseUrl."/rest/V1/qp/shippingmethodslist";
curl_setopt($curl, CURLOPT_URL, $apiurl);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
$output = curl_exec($curl);
curl_close($curl);
?>

<span type="hidden" id="productId" name="productId"><?php echo $proid ?></span>
<span type="hidden" id="productImage" name="productImage"><?php echo $baseUrl.''.$proimage ?></span>
<span type="hidden" id="baseurl" name="baseurl"><?php echo $baseUrl?></span>
<span type="hidden" id="productTitle" name="productTitle"><?php echo $proname ?></span>
<span type="hidden" id="productShipping" name="productShipping"></span>
<span type="hidden" id="token" name="token"></span>
<span type="hidden" id="shippingmethodshtml" name="shippingmethodshtml"><?php echo $output ?></span>
<?php
$colors = array();
$colorsval = array();
foreach ($attributes as $option) {
        $colors[] = $option['label'];
        $colorsval[] = $option['value'];
}
sort($colors);
?>
<script type="text/javascript">
    require([ 'jquery', 'jquery/ui'], function($){

      $(document).ready(function($) {
        var productImage = <?php echo $proimage ?>;
        setTimeout(
          function()
          {
            jQuery("#productId").text(productImage);
          }, 5000);
        $(".oneclick-button").click(function(){
          var i = 0;
          var visual = jQuery(".swatch-attribute.visual").length;
          var j = 0;
          var max = jQuery(".swatch-attribute").length;
          var keys = [];
          var indexing = [];
          while (i < max) {
              keys.push(jQuery(jQuery(".swatch-opt .swatch-attribute:nth-child("+i+")")).find(":selected").text());
              indexing.push(jQuery(".swatch-opt .swatch-attribute:nth-child("+i+") .swatch-attribute-label").text());
              i++;
          }
          while (j < visual) {
            if(j<visual && jQuery(".swatch-attribute-options").find(".swatch-option.selected").attr("aria-label")){
              keys.push(jQuery(".swatch-attribute-options").find(".swatch-option.selected").attr("aria-label"));
              indexing.push(jQuery(".swatch-opt .swatch-attribute:nth-child("+i+") .swatch-attribute-label").text());
                j++;
            }
          }
          var k = 0;
          var d;
          while (k < max) {
            if(k+1 == max){d = array(indexing[k] => keys[k]);}else{d = array(indexing[k] => keys[k],);}
            k++;
          }
        });
      }
); });
</script>
<script>
function myFunction() {
  var objection = JSON.parse('<?php echo json_encode($options) ?>');
  alert(obj.toSource());
  document.getElementById("demo").innerHTML = "Hello World";
}
</script>
<script type="text/javascript">
function triggerIFrame() {
      var productId = jQuery("#productId").text();
      var productImage = jQuery("#productImage").text();
      var productQuantity = jQuery(".qty #qty").val();
      var productPrice = jQuery(".product-info-price .price-wrapper ").attr("data-price-amount");
      var productTitle = jQuery("#productTitle").text();
      var productShipping = jQuery("#shippingmethodshtml").text();
      var baseurl = jQuery("#baseurl").text();
      var i = 0;
      var visual = jQuery(".swatch-attribute.visual").length;
      var j = 0;
      var max = jQuery(".swatch-attribute").length;
      var keys = [];
      var indexing = [];
      while (i < max) {
          keys.push(jQuery(jQuery(".swatch-opt .swatch-attribute:nth-child("+i+")")).find(":selected").text());
          indexing.push(jQuery(".swatch-opt .swatch-attribute:nth-child("+i+") .swatch-attribute-label").text());
          i++;
      }
      while (j < visual) {
        if(j<visual && jQuery(".swatch-attribute-options").find(".swatch-option.selected").attr("aria-label")){
          keys.push(jQuery(".swatch-attribute-options").find(".swatch-option.selected").attr("aria-label"));
          indexing.push(jQuery(".swatch-opt .swatch-attribute:nth-child("+i+") .swatch-attribute-label").text());
            j++;
        }
      }
      var indexed = indexing.filter(function(v){return v!==''});
      var valued = keys.filter(function(v){return v!==''});

      var k = 0;
      var resultant = {};
      while (k < max) {
          resultant[indexed[k]] = valued[k];
          k++;
      }
      var attris = '';
      for (var key in resultant) {
          var value = resultant[key];
          attris = attris+'"'+key+'":"'+value+'",';
      }
      var streamhit = 'products=[{"id":"'+productId+'","src":"'+productImage+'","quantity":"'+productQuantity+'","attributes":[{'+attris+'}],"price":'+productPrice+',"title":"'+productTitle+'"}]&price='+productPrice+'&currency=PKR&url=https://sandbox.wordpress.qisstpay.com/wp-json/qisstpay/teez/&shipping_total=0&tax=0&shipping_methods='+productShipping;
      streamhit = streamhit.replace(',}', '}');

      var streatfinal = btoa(unescape(encodeURIComponent(streamhit)));
      var baseuri = btoa(unescape(encodeURIComponent(baseurl)));
      var bata = 'https://sandbox.tezcheckout.qisstpay.com/?identity-token='+baseuri+'\&'+'queryUrl=';
      var datastreaming = bata+streatfinal;
      let unescapedurl=_.unescape(datastreaming);
      jQuery("#qisttpayifram").attr('src', unescapedurl);
      window.addEventListener('message', function(e) {
                      // Get the sent data
                      const data = e.data;

                      try {
                          if(data.qp_flag_teez == true){
                              window.location.href= data.link;
                              ///form Submit
                          } else if(data.qp_flag_teez == false) {
                              jQuery('.qp8911_modal').hide();
                              jQuery('body').css('position', 'initial');
                              jQuery('body').css('width', 'initial');
                              jQuery('.qisttpayifram').attr('src', null);
                          }
                      } catch(e){
                          return;
                      }
                  });
      jQuery('#qp8911_bootstrapModal').show();
      jQuery('#closed').click(function(){
          jQuery('#qp8911_bootstrapModal').hide();
      })
    }
</script>
<div class="qp8911_modal" id="qp8911_bootstrapModal" role="dialog">
    <div class="qp8911_modal-dialog qp8911_modal-dialog-centered" role="document" >
        <div class="qp8911_modal-content col-md-8 qp-custom-mage-design">
            <div class="modal-header"></div>
            <div class="qp8911_modal-body">
                <div class="form-popup" id="myForm" style="border: 1px solid gainsboro;top: 0px;background: white;border-radius: 4px; display: none">
                    <form action="" method="post" class="form-container" id="myformtobesubmit">
                        <input type="hidden" name="order" value="lkld">
                    </form>
                </div>
                <iframe id="qisttpayifram" width="100%" height="100%"  src="" frameborder="0" allowfullscreen style="background: #FFFFFF;" ></iframe>

            </div>
        </div>
    </div>
</div>
